services:
  pihole:
    container_name: pihole
    env_file: .env
    image: pihole/pihole:latest
    # Only expose the web UI; do NOT expose 53/67
    ports:
      - ${DNS_BIND_IP}:8088:80
      - ${DNS_BIND_IP}:8443:443
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp

    volumes:
      - "./etc-pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
