services:
  gitlab:
    image: gitlab/gitlab-ce:18.10.5-ce.0
    container_name: Gitlab
    hostname: "gitlab.example.com"

    env_file:
      - .env
    ports:
      - "6000:80"
      - "6443:443"
      - "22:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    shm_size: "256m"
    restart: unless-stopped
